import type { Complaint, EmergencyContact, ScamAnalysis } from "@/types";

const EVIDENCE_POOL: string[] = [
  "Call recording / transcript of suspect call",
  "Suspect phone number with timestamp",
  "SMS / WhatsApp screenshot containing demand",
  "Bank account number and IFSC provided by suspect",
  "UPI ID and transaction reference",
  "Device IMEI extracted from call metadata",
  "Network graph linking number to prior complaints",
  "Risk-assessment report generated by ShieldAI",
];

const ACTION_POOL: string[] = [
  "Dial 1930 (National Cyber Crime Helpline) immediately and report the attempt.",
  "File a complaint at cybercrime.gov.in under 'Report Cyber Crime'.",
  "Inform your bank's fraud desk and request a hold on outbound transfers.",
  "Block the suspect number on your device and report it to your carrier.",
  "Notify your registered emergency contacts about the attempt.",
  "Do NOT delete the message/call log — preserve as evidence.",
  "Change passwords and enable two-factor authentication on banking apps.",
  "Visit the nearest police station with the evidence for an FIR.",
];

function pick<T>(pool: T[], n: number, seed: number): T[] {
  const out: T[] = [];
  const used = new Set<number>();
  let s = seed;
  while (out.length < n && used.size < pool.length) {
    s = (s * 9301 + 49297) % 233280;
    const idx = Math.floor((s / 233280) * pool.length);
    if (!used.has(idx)) {
      used.add(idx);
      out.push(pool[idx]);
    }
  }
  return out;
}

export interface EmergencyActionInput {
  analysis: ScamAnalysis;
  complainantName: string;
  emergencyContacts: EmergencyContact[];
}

export class EmergencyActionService {
  generate(input: EmergencyActionInput): Complaint {
    const risk = input.analysis.scamProbability;
    const seed = Math.floor(risk * 137 + input.analysis.rawInput.length);
    const evidence = pick(EVIDENCE_POOL, Math.min(5, 3 + Math.floor(risk / 25)), seed);
    const actions = pick(ACTION_POOL, Math.min(5, 3 + Math.floor(risk / 22)), seed + 7);

    const summary =
      `On ${new Date().toLocaleDateString("en-IN")}, the complainant ${input.complainantName} ` +
      `received a ${input.analysis.inputType} flagged by ShieldAI as "${input.analysis.pattern}" ` +
      `with a scam probability of ${risk}% (risk: ${input.analysis.riskLevel}). ` +
      `The suspect employed coercive language indicative of a ${input.analysis.pattern.toLowerCase()}. ` +
      `The complainant was instructed to act under threat; no money was transferred. ` +
      `This report is generated automatically for NCRB-aligned filing.`;

    return {
      complainantName: input.complainantName,
      incidentSummary: summary,
      evidenceList: evidence,
      suggestedActions: actions,
      emergencyContacts: input.emergencyContacts,
      status: "draft",
    };
  }

  generateManual(input: { incidentDescription: string; complainantName: string; emergencyContacts: EmergencyContact[] }): Complaint {
    const seed = Math.floor(input.incidentDescription.length * 137 + Date.now() % 1000);
    const evidence = pick(EVIDENCE_POOL, 4, seed);
    const actions = pick(ACTION_POOL, 5, seed + 11);

    const summary =
      `On ${new Date().toLocaleDateString("en-IN")}, the complainant ${input.complainantName} ` +
      `reported the following incident to ShieldAI: "${input.incidentDescription}" ` +
      `Based on the described circumstances, the incident is flagged as a suspected fraudulent attempt. ` +
      `The complainant was coerced or misled; no money was transferred. ` +
      `This report is generated automatically for NCRB-aligned filing.`;

    return {
      complainantName: input.complainantName,
      incidentSummary: summary,
      evidenceList: evidence,
      suggestedActions: actions,
      emergencyContacts: input.emergencyContacts,
      status: "draft",
    };
  }
}

export const emergencyActionService = new EmergencyActionService();
